#!/bin/bash

echo "checking files formatting according to .clang-format...\n"

#TODO: list unformatted files 
git diff --cached --name-only --diff-filter=ACMRT |
  grep "\.[cmh]$" |
  xargs -n1 clang-format -style=file -output-replacements-xml |
  grep "<replacement " >/dev/null
if [ $? -ne 1 ]; then 
    echo "Commit did not match clang-format"
    echo "find . -iname \*.h -o -iname \*.cpp -o -iname \*.hpp | xargs clang-format -i"
    echo "to apply auto-formatting" 
    exit 1
fi

echo "file formatting is fine"